### ISSUE TITLE
to disable subdomain

### ISSUE THREAD

**Issue by lubimow** [Automattic/lazy-load#4]
I can not see images on mobile site wp-touch
how can I fix it?

**Comment by BrookeDot** [comment]
I'm going to go ahead and close this issue out since it's a few years old. If you are still looking for a way to disable LazyLoad for a specific plugin/function, you'll find an example here:
https://github.com/Automattic/lazy-load/blob/master/wpcom-helper.php#L3

I'm not sure the exact function you'll need for `wp touch` though.
